[package]
name = "um"
version = "0.1.0"
authors = ["Per Blesh√∏y Nielsen <per.nielsen@productmadness.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
